version: '3.0'
services:
  db:
    image: "postgres" 
    ports:
      - "5432:5432"
    env_file:
      - db/database.env 
      
  python:
    build: app/.
    depends_on:
      - db
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

